version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: db_jobboard
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_DIALECT: mysql
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db_jobboard
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  web:
    build:
      context: ./site
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data: