-- MySQL Script generated by MySQL Workbench
-- Sun Dec 22 21:15:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
    UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema db_job_board
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_job_board
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_job_board` DEFAULT CHARACTER SET utf8;
USE `db_job_board`;
-- -----------------------------------------------------
-- Table `db_job_board`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_job_board`.`company` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `description` VARCHAR(45) NOT NULL,
    `logo` BLOB NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1;
-- -----------------------------------------------------
-- Table `db_job_board`.`employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_job_board`.`employer` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `surname` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `company_id` INT NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`, `company_id`),
    INDEX `fk_employer_company1_idx` (`company_id` ASC) VISIBLE,
    CONSTRAINT `fk_employer_company1` FOREIGN KEY (`company_id`) REFERENCES `db_job_board`.`company` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 1;
-- -----------------------------------------------------
-- Table `db_job_board`.`advertisement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_job_board`.`advertisement` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(45) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `address` VARCHAR(45) NOT NULL,
    `employment_contract_type` VARCHAR(45) NOT NULL,
    `country` VARCHAR(45) NOT NULL,
    `wage` FLOAT NOT NULL,
    `tag` VARCHAR(45) NULL,
    `employer_id` INT NOT NULL,
    `company_id` INT NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`, `employer_id`, `company_id`),
    INDEX `fk_advertisement_employer1_idx` (`employer_id` ASC, `company_id` ASC) VISIBLE,
    CONSTRAINT `fk_advertisement_employer1` FOREIGN KEY (`employer_id`, `company_id`) REFERENCES `db_job_board`.`employer` (`id`, `company_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 1;
-- -----------------------------------------------------
-- Table `db_job_board`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_job_board`.`user` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `surname` VARCHAR(45) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `isAdmin` TINYINT NOT NULL DEFAULT 0,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1;
-- -----------------------------------------------------
-- Table `db_job_board`.`job_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_job_board`.`job_application` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `cv` MEDIUMBLOB NOT NULL,
    `cover_letter` MEDIUMBLOB NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `user_id` INT NOT NULL,
    `advertisement_id` INT NOT NULL,
    `employer_id` INT NOT NULL,
    `company_id` INT NOT NULL,
    PRIMARY KEY (
        `id`,
        `user_id`,
        `advertisement_id`,
        `employer_id`,
        `company_id`
    ),
    INDEX `fk_job_application_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_job_application_advertisement1_idx` (
        `advertisement_id` ASC,
        `employer_id` ASC,
        `company_id` ASC
    ) VISIBLE,
    CONSTRAINT `fk_job_application_user1` FOREIGN KEY (`user_id`) REFERENCES `db_job_board`.`user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_job_application_advertisement1` FOREIGN KEY (
        `advertisement_id`,
        `employer_id`,
        `company_id`
    ) REFERENCES `db_job_board`.`advertisement` (`id`, `employer_id`, `company_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 1;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;